CREATE TABLE `myTable` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `Login` varchar(255) default NULL,
  `Senha` varchar(255),
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Kelly Pugh","MMB31TVR4XT"),("Hiram Haley","KPG66JSS1MX"),("Harlan Wiggins","VHG15VDX0JE"),("Emery Sellers","CCN06OGX9XF"),("Baxter Lowe","RVW34VOF8LV"),("Quentin Benjamin","FAI47PTN2ZJ"),("Upton Greer","KNJ85YHG8QC"),("Alvin Delgado","KAX39RKP9QL"),("Nissim Drake","FRR01GCQ0JF"),("Colin Lang","DRE81JSU5EY");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Kieran Richardson","JZN45ZXO7UI"),("Zahir Poole","FCY30HMY8ZZ"),("Isaiah Vang","PUD69VHF1AY"),("Jesse Shields","IFW37XPK9JK"),("Dennis Stone","SAF50KNW7HR"),("Amery Holland","IFX33WDR6YR"),("Abdul Dickson","MIA43COY0RN"),("Amos Cotton","XSG49QBB6DU"),("Curran Wynn","QHP10XDK1KI"),("Chaney Barron","YRB62GPB1AX");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Ezra Huber","FBJ39XLQ2IL"),("Daquan Cummings","NLS48DMF5OV"),("Mason Daniels","BIB49XSL4NJ"),("Alec Marshall","PYT37WZH7KE"),("Elmo Cardenas","NZV44TNQ6TH"),("Ian Sutton","PYA84JMK0ZI"),("Callum Salazar","QIP90OIM8EX"),("Dustin Mcdaniel","NQA70WER1GU"),("Keaton Malone","ARW93NFT5ES"),("Alfonso Salinas","HRR97VLV6IZ");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Trevor Small","SQA19WSK0HO"),("Ferdinand Moran","FGQ03QBZ2MF"),("Erasmus Schmidt","IAL60SEV5PE"),("Brady Brock","KBR08FRT0PJ"),("Chester Shepard","RDW40EJE8SW"),("Jin Cervantes","VQT64JLD8QV"),("Carson Wall","AUD72YOP6LA"),("Perry Rodriguez","MKB80HUM7XT"),("Thomas Herring","XTM45YJJ0FF"),("Ivan Harper","FDC59TCO0CO");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Derek Galloway","CIU11OJD0GQ"),("Mufutau Bauer","EVG22YFH2UV"),("Abdul Blanchard","CDK28PPE1ZS"),("Kenneth Hester","HFO53KYA8GJ"),("Graiden Slater","YMP62DFH3GX"),("Declan Cote","WMC30WVK2RY"),("Castor Dean","DXX63SLF9IZ"),("Fletcher Jacobs","IEI07VLP6RS"),("Leonard Gates","QJG63GPU7BX"),("Howard Luna","TUO47NTM3UR");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Isaiah Meadows","HCQ24MVE8VS"),("Vladimir Howe","FOD81USK5UQ"),("Seth Oneill","HIY00GGK1ZQ"),("Honorato Perry","WQI53GSA8HJ"),("Wyatt Aguirre","MTK55OEB1ZB"),("Thane Faulkner","NSG24ERC0DE"),("Anthony Jensen","EQO81KTS2NX"),("Quinn Robbins","VCU40PIV7HY"),("Charles Vega","MLA15ALA0TY"),("Lester Fischer","TKY07PZV0YD");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Reese Porter","YWD59STK8HO"),("Harrison Watson","AID08OKW8IS"),("Herman Boone","NRQ45KEW3WT"),("Seth Evans","UGW18PVJ9QJ"),("Gil Rowe","DTE66SUP0IJ"),("Martin Stuart","TNB18XEI9KW"),("Igor Atkinson","SLF59DEK0BR"),("Christian Holland","MIS62KXE0KK"),("Fulton Greene","WAM07SEQ8HU"),("Malcolm Mills","IEE59BTH8GA");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Gary Hoffman","EDZ42SHF4FV"),("Barclay Arnold","PJL69XAA4UJ"),("Russell Vincent","BLH20ZLC9ZP"),("Keegan Ratliff","LHS13RLT1PG"),("Vincent Cummings","HLJ53FND9IL"),("Christian Gray","BJO61VJS1YW"),("Ferris Haynes","SHT59QGC4UB"),("Colorado Finley","YTY64ZDQ2HP"),("Igor Dorsey","YTG70IHB4WV"),("Cedric Crosby","NPF36WML0VC");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Clayton Pickett","FHL41SIL5LO"),("Lucian Acosta","SRF01QDZ1AO"),("Coby Mitchell","BDN52HTD0SH"),("Keith Dudley","ZKK84HJO3HD"),("Ryan Aguilar","SHP82XFY8CP"),("Orson Golden","YQS21KDT5QN"),("Derek Knight","STI31SRG7GN"),("Todd Warren","WPT17IWR1BA"),("Lucas Cortez","KZT25SJS5BN"),("Ethan Lyons","AUI16QBF6DF");
INSERT INTO `myTable` (`Login`,`Senha`) VALUES ("Hyatt Waller","NKS62SUS0JA"),("Leo Barton","DQO81GHV2YU"),("Allistair Bennett","RRH19HNY2CK"),("Brent Gutierrez","KFI59CKT8PZ"),("Clarke Thomas","NOP43AQD1GT"),("Branden Mcmillan","VNZ75FVR7GA"),("Kato Dudley","QBX16AVW5BS"),("Thane Atkinson","FGY45YAF8GH"),("Mohammad Moore","RZL42ZVI7LL"),("Alfonso Burnett","QBZ50NXO5PN");